### ISSUE TITLE
elevenlabs issue

### ISSUE THREAD

**Issue by kamalkech** [KoljaB/AIVoiceChat#11]
elevenlabs.set_api_key("")
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'elevenlabs' has no attribute 'set_api_key'

Edit: you posted your key, I removed it but pls change it as soon as possible in case someone saw it

**Comment by KoljaB** [comment]
For the problem: this is old code, elevenlabs changed their api.

Use "pip install elevenlabs==0.2.27" for this script or change it [to the new api](https://github.com/elevenlabs/elevenlabs-python?tab=readme-ov-file#v0x-to-v1x-migration-guide)

**Comment by KoljaB** [comment]
Again you posted your key, I removed it but it is still visible in the history pls change it as fast as you can. I can't remove it completely from here.

**Comment by kamalkech** [comment]
i found many issues on this project not just this, i guess need to update ur project

**Comment by kamalkech** [comment]
@kamalkech me too after ur last comment
