### ISSUE TITLE
Playback voice stops & starts

### ISSUE THREAD

**Issue by 1030** [KoljaB/AIVoiceChat#4]
Hello, this is incredible! I got it set up fairly quickly. It works great, except that the voice only says a few words at a time, then pauses for a few seconds, then continues, then pauses etc.

Would you have any advice for how to eliminate this playback problem? My internet speed is fairly good, so I doubt it's that.

Thanks for all your work on this, it's the best execution I've seen of this idea to date.

**Comment by KoljaB** [comment]
Just tried it with my 10Mbps connection, it worked smoothly here. Hard to say what goes wrong. Do you upgrade to the latest elevenlabs python library (pip install --upgrade elevenlabs)? The script uses the elevenlabs API [exactly like documented](https://github.com/elevenlabs/elevenlabs-python#-streaming). Maybe their servers are overloaded...

**Comment by 1030** [comment]
I figured out the problem! I was trying to use "eleven_multilingual_v2" which currenly doesn't support streaming! See https://github.com/elevenlabs/elevenlabs-python/issues/114

I switched the model back to monolingual v1 and the stuttering playback fixed!

**Comment by KoljaB** [comment]
Ah, good to know that. And sad they still dont support it for their most capable model. Will close the issue then, thx for reporting,.
